expression ::= number
            | expression '/' expression
            | expression '*' expression
            | expression '+' expression
            | expression '-' expression
            ;

addition_expression ::= multiplication_expression
                      | addition_expression '+' multiplication_expression
                      | addition_expression '-' multiplication_expression
                      ;

multiplication_expression ::= number
                            | number '*' multiplication_expression
                            | number '/' multiplication_expression
                            ;

number ::= T_INT | T_DOUBLE;